Algoritmo "Calcular o resto de uma divisão"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 24/08/2021
Var
// Seção de Declarações das variáveis 
N, R :Inteiro;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval ("digite um número inteiro: ")
leia (N)
R <- N mod 2
escreval ("O Resto da Divisão de " ,N, " é " ,R)


Fimalgoritmo